### ISSUE TITLE
SqliteStorage class body dereferences sqlite3 at import time, breaking huey on Python builds without _sqlite3

### ISSUE THREAD

**Issue by jc-louis** [coleifer/huey#908]
huey/storage.py guards the sqlite3 import:

```py
    try:
        import sqlite3
    except ImportError:
        sqlite3 = None
```
but the SqliteStorage class body then evaluates it unconditionally at import time:

```py
    integrity_error = sqlite3.IntegrityError
    sqlite_version_info = sqlite3.sqlite_version_info
```

On a Python built without the _sqlite3 extension module, simply importing huey (e.g. from huey import RedisHuey) fails with:

```
  File "huey/storage.py", line 820, in SqliteStorage
    integrity_error = sqlite3.IntegrityError
AttributeError: 'NoneType' object has no attribute 'IntegrityError'
```

This makes huey unimportable even when SqliteStorage is never used. It worked in 3.2.1 and broke in 3.3.x, so it is a regression for anyone on a slim/minimal Python image. We hit it in production with RedisHuey and had to pin huey<3.3.

The try/except fallback suggests sqlite3 is meant to be optional, so the class attributes probably should be resolved lazily, or the whole SqliteStorage definition guarded by "if sqlite3 is not None".

Introduced by commit 403ee65c147573d22244bda2c0aecb5c429fbe84 ("Doc cleanups.", 2026-07-22), which added those two class attributes. First released in 3.3.0.

**Comment by coleifer** [comment]
Sorry for the breakage, I honestly didn't realize people ran cpython w/o SQLite these days. Patched and sending out a 3.3.3 w/the fix.

**Comment by tcely** [comment]
Somewhat related to this; while splitting up `storage.py` and checking it (#912), I noticed that there is a guard in `__init__` for `cysqlite` but no such guard exists for `sqlite3`.

https://github.com/coleifer/huey/blob/539115620655ba72095e6a3103fff154a565354c/huey/storage.py#L1035-L1043

https://github.com/coleifer/huey/blob/539115620655ba72095e6a3103fff154a565354c/huey/storage.py#L817-L868

Would it be helpful to add a check for `sqlite3 is None` so that we don't need to use `getattr` when the exception wasn't raised?

We would move the assignment into `__init__` after such a guard was added.

**Comment by coleifer** [comment]
No, I think it's fine, `sqlite3` not installed is pretty unusual and there's no "pip install sqlite3" so it's up to the user at that point.
